// Pascal Triangle
// https://leetcode.com/problems/pascals-triangle-ii/

// https://leetcode.com/problems/pascals-triangle-ii/discuss/2749774/simple-maths-on-2-approaches

// We can observe that the Nth row of the Pascals triangle consists of following sequence:
// NC0, NC1, ......, NCN - 1, NCN

// Since, NC0 = 1, the following values of the sequence can be generated by the following equation:
// NCr = (NCr - 1 * (N - r + 1)) / r where 1 ≤ r ≤ N


#include<bits/stdc++.h>
using namespace std;

vector<int> getRow(int N) {
        
    vector<int>v;
    v.push_back(1);
    long long prev = 1;

    for (int i = 1; i <= N; i++) {
        // nCr = (nCr-1 * (n - r + 1))/r
        long long curr = (prev * (N - i + 1)) / i;
        v.push_back(curr);
        prev = curr;
    }
    return v;
}