#include<bits/stdc++.h>
using namespace std;

// https://leetcode.com/problems/find-the-difference/
// String t is generated by random shuffling string s and then add one more letter at a random position.
// Return the letter that was added to t.

char findTheDifference(string s, string t) 
{
    char ans=0;
    for(char c: s)
        ans=ans^c;
    for(char c:t)
        ans=ans^c;
    
    return ans;
}

int main()
{
    string s,t;
    cin>>s>>t;
    cout<<findTheDifference(s,t);
}